# The URL the site will be built for
base_url = "https://emilyaviva.com"
title = "Emily Aviva Kapor-Mater"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Gutenberg
highlight_code = true
highlight_theme = "solarized-light"

generate_rss = true
rss_limit = 20

[extra]
# Put all your custom variables here
